### ISSUE TITLE
Swap Data::UUID for PurePerl implementation?

### ISSUE THREAD

**Issue by MCRayRay** [fluent/fluent-logger-perl#25]
Hi, I've noticed you've listed Data::UUID as a dependency. Would there be any chance of you switching to [UUID::Tiny](https://metacpan.org/pod/UUID::Tiny) instead? It removes the C dependency and, this is just my opinion, the API is more perl-ish.

**Comment by fujiwara** [comment]
I understood. I switched to use UUID::Tiny on v0.24. Thank you!
